version: '3.8'

services:

  web:
    build: .
    ports:
      - 5001:5000
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=server
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - worker

  worker:
    build: .
    command: celery --app server.tasks.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
